
version: "3.9"
services:
  consul:
    image: consul:latest
    command: agent -dev -client=0.0.0.0 -bind=0.0.0.0 -config-dir=/etc/consul.d
    ports:
      - "8500:8500"
      - "8600:8600"
    volumes:
      - ./consul-config:/etc/consul.d

  nomad:
    image: hashicorp/nomad:latest
    command: agent -dev -bind=0.0.0.0 -client=0.0.0.0
    ports:
      - "4646:4646" # Nomad UI
    depends_on:
      - consul
