{
 "title": "HashiCorp Nomad",
 "description": "A dashboard for HashiCorp Nomad https://www.nomadproject.io/",
 "tags": [ "HashiCorp" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "query": {
     "query": "label_values(up{job=\"nomad\"},env)"
    }
   },
   {
    "name": "client",
    "query": {
     "query": "label_values(nomad_client_uptime{env=\"$env\"}, instance)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(nomad_client_allocs_cpu_allocated{env=\"$env\",instance=~\"$client\"},exported_job)"
    }
   },
   {
    "name": "group",
    "query": {
     "query": "label_values(nomad_client_allocs_cpu_allocated{env=\"$env\",instance=~\"$client\",exported_job=~\"$job\"},task_group)"
    }
   },
   {
    "name": "task",
    "query": {
     "query": "label_values(nomad_client_allocs_cpu_allocated{env=\"$env\",instance=~\"$client\",exported_job=~\"$job\",task_group=~\"$group\"},task)"
    }
   },
   {
    "name": "alloc_id",
    "query": {
     "query": "label_values(nomad_client_allocs_cpu_allocated{env=\"$env\",instance=~\"$client\",exported_job=~\"$job\",task_group=~\"$group\",task=~\"$task\"},alloc_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_nomad_autopilot_healthy{env=\"$env\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Fault tolerance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_nomad_autopilot_failure_tolerance{env=\"$env\"}",
     "legendFormat": "fault tolerance"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_nomad_job_status_running{env=\"$env\"}",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Allocations",
   "type": "table",
   "gridPos": { "h": 12, "w": 20, "x": 4, "y": 5 },
   "targets": [
    {
     "expr": "nomad_nomad_job_summary_complete{env=\"$env\"}",
     "legendFormat": "complete"
    },
    {
     "expr": "nomad_nomad_job_summary_failed{env=\"$env\"}",
     "legendFormat": "failed"
    },
    {
     "expr": "nomad_nomad_job_summary_lost{env=\"$env\"}",
     "legendFormat": "lost"
    },
    {
     "expr": "nomad_nomad_job_summary_starting{env=\"$env\"}",
     "legendFormat": "starting"
    },
    {
     "expr": "nomad_nomad_job_summary_queued{env=\"$env\"}",
     "legendFormat": "queued"
    },
    {
     "expr": "nomad_nomad_job_summary_running{env=\"$env\"}",
     "legendFormat": "running"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_nomad_job_status_pending{env=\"$env\"}",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_nomad_job_status_dead{env=\"$env\"}",
     "legendFormat": "Dead"
    }
   ]
  },
  { "title": "Raft", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Raft Dispatch Log",
   "type": "timeseries",
   "description": "Time to write log, mark in flight, and start replication to followers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "nomad_raft_leader_dispatchLog{env=\"$env\",quantile=\"0.9\"}",
     "legendFormat": "Time"
    },
    {
     "expr": "increase(nomad_raft_leader_dispatchNumLogs{env=\"$env\"}[$__rate_interval])",
     "legendFormat": "Logs"
    }
   ]
  },
  {
   "title": "Raft Commit Time",
   "type": "timeseries",
   "description": "Time difference between when a message was first passed into Raft and when the resulting commit took place on the leader",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "nomad_raft_commitTime{env=\"$env\",quantile=\"0.9\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Raft Apply Count",
   "type": "timeseries",
   "description": "Number of Raft transactions - general indicator of the write load on the servers.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(nomad_raft_apply{env=\"$env\"}[$__rate_interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Raft Append Entries",
   "type": "timeseries",
   "description": "The time it takes for a Raft transaction to be replicated to a quorum of followers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "nomad_raft_rpc_appendEntries{env=\"$env\",quantile=\"0.9\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Raft Applied Index",
   "type": "bargauge",
   "description": "Current index applied to FSM",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_raft_appliedIndex{env=\"$env\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Raft FSM apply",
   "type": "timeseries",
   "description": "Time it takes for a server to apply Raft entries to the internal state machine.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "nomad_raft_fsm_apply{env=\"$env\",quantile=\"0.9\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Vault", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Server token TTL",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "nomad_nomad_vault_token_ttl{env=\"$env\"}",
     "legendFormat": "ttl"
    }
   ]
  },
  {
   "title": "Tokens",
   "type": "timeseries",
   "description": "Time elapsed to manipulate Vault tokens",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "nomad_nomad_vault_create_token{quantile=\"0.9\"}",
     "legendFormat": "create"
    },
    {
     "expr": "nomad_nomad_vault_lookup_token{quantile=\"0.9\"}",
     "legendFormat": "lookup"
    },
    {
     "expr": "nomad_nomad_vault_revoke_token{quantile=\"0.9\"}",
     "legendFormat": "revoke"
    }
   ]
  }
 ]
}