{
 "title": "Hello Service Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Hello Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hello Service Uptime (1h)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(hello_service_successful_responses[1h])) / sum(rate(hello_service_total_requests[1h])) * 100"
    }
   ]
  },
  {
   "title": "Hello Service Response Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(hello_service_successful_responses[5m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(hello_service_failed_responses[5m])",
     "legendFormat": "Failed"
    }
   ]
  },
  { "title": "Response Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Response Service Uptime (1h)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(response_service_successful_responses[1h])) / sum(rate(response_service_total_requests[1h])) * 100"
    }
   ]
  },
  {
   "title": "Response Service Response Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(response_service_successful_responses[5m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(response_service_failed_responses[5m])",
     "legendFormat": "Failed"
    }
   ]
  }
 ]
}