services:
  hello-service:
    image: ${TF_VAR_dockerhub_id}/helloservice:0.0.2
    container_name: helloservice
    build: ./HelloService
    environment:
      RESPONSE_SERVICE_HOST: responseservice
    ports:
      - "9999:5050"
  response-service:
    image: ${TF_VAR_dockerhub_id}/responseservice:0.0.2
    container_name: responseservice
    build: ./ResponseService
    ports:
      - "6060:6060"
